# -*- python -*-
Import('MODE', 'env')
LocalEnv = env.Clone()

### Setting up environment
if MODE == 'debug':
    LocalEnv.MergeFlags({'CCFLAGS':['-g','-Wall']})

input_files = Glob('*.cpp')

project_library_paths = {'LIBPATH':['#lib/Debug']}
LocalEnv.MergeFlags(project_library_paths)

project_libs = {'LIBS':'Core'}
LocalEnv.MergeFlags(project_libs)

if MODE == 'debug':
    LocalEnv.SharedLibrary(target='#Plugins_d/Simple', source=input_files)
