# -*- python -*-
Import('MODE', 'env')
LocalEnv = env.Clone()

### Setting up environment
if MODE == 'debug':
    LocalEnv.MergeFlags({'CCFLAGS':['-g','-Wall']})

project_include_paths = {'CPPPATH': ['#OViSEdotSceneBase']}
env.MergeFlags(project_include_paths)
project_library_paths = {'LIBPATH':['#lib/Debug']}
env.MergeFlags(project_library_paths)

if MODE == 'debug':
    project_libs = {'LIBS':['OViSEdotSceneBase']}
env.MergeFlags(project_libs)

## Input files
input_files = Glob('*.cpp')

if MODE == 'debug':
    env.Library(target='#lib/Debug/OViSEdotSceneInterpreter', source=input_files)

