#ifndef ADD_MESH_DIALOG
#define ADD_MESH_DIALOG

/**
@file
Subclass of AddMeshDialog, which is generated by wxFormBuilder.
*/

#include "MainFrameBase.h"
#include <Ogre.h>
#include "../OgreMediator/OgreMediator.h"

class MeshDialogFrameListener : public Ogre::FrameListener
{
public:
	MeshDialogFrameListener(Ogre::SceneManager *scnMgr);
    ~MeshDialogFrameListener();

protected:
    bool frameStarted(const Ogre::FrameEvent& evt);
    bool frameEnded(const Ogre::FrameEvent& evt);

    Ogre::SceneManager *mSceneManager;
};



/** Implementing AddMeshDialog */
class OViSEAddMeshDialog : public AddMeshDialog
{
protected:
    // Handlers for AddMeshDialog events.
    void OnCloseDialog( wxCloseEvent& event );
    void OnMeshListSelect( wxCommandEvent& event );
    void OnOkClick( wxCommandEvent& event );
    void OnApplyClick( wxCommandEvent& event );
    void OnCancelClick( wxCommandEvent& event );
    void OnRenderWinResize( wxSizeEvent& event );

    void updateMeshList();
        
public:
    /** Constructor */
    OViSEAddMeshDialog( wxWindow* parent, wxWindowID id );
	void InitOgre();
    virtual ~OViSEAddMeshDialog();

	// needs to be public to be updated from MainFrame (thanks to Linux...)
	Ogre::RenderWindow* mRenderWin;

private:
    Ogre::SceneManager *mSceneMgr;
	QualifiedName qSceneMgr;
	wxWindow *mRenderWinWX;
    Ogre::Camera *mCam;
    Ogre::Light *mLight;
	QualifiedName qMeshNode;
    Ogre::SceneNode *mMeshNode;

    MeshDialogFrameListener *mListener;

    wxString lastSelected;

	Ogre::String GetOgreHandle();
};

#endif // ADD_MESH_DIALOG
