#ifndef __OViSEAddMeshDialog__
#define __OViSEAddMeshDialog__

/**
@file
Subclass of AddMeshDialog, which is generated by wxFormBuilder.
*/

#include "GUIFrame.h"
#include "wxOgreRenderWindow.h"
#include "OViSESceneHandling.h"

/** Implementing AddMeshDialog */
class OViSEAddMeshDialog : public AddMeshDialog
{
protected:
	// Handlers for AddMeshDialog events.
	void OnClose( wxCloseEvent& event );
	void OnMeshListSelect( wxCommandEvent& event );
	void OnOkClick( wxCommandEvent& event );
	void OnApplyClick( wxCommandEvent& event );
	void OnCancelClick( wxCommandEvent& event );

	void updateMeshList();
	
public:
	/** Constructor */
	OViSEAddMeshDialog( wxWindow* parent );

private:
	Ogre::SceneManager *mSceneMgr;
	OViSESceneHandling *mSceneHandler;
	wxOgreRenderWindow *mRenderWin;
	Ogre::Camera *mCam;
};

#endif // __OViSEAddMeshDialog__
