#ifndef __OViSEAttachSceneDialog__
#define __OViSEAttachSceneDialog__

/**
@file
Subclass of AttachSceneDialog, which is generated by wxFormBuilder.
*/

// Solution's includes
#ifndef GUIFRAME_USED
#define GUIFRAME_USED
#include "GUIFrame.h"
#endif

#ifndef OVISE_STRINGCONVERTER_USED
#define OVISE_STRINGCONVERTER_USED
#include "OViSEStringConverter.h"
#endif

// Include WX
#ifndef WX_STRING_USED
#define WX_STRING_USED
#include <wx/string.h>
#endif

#ifndef WX_ARRAYSTRING_USED
#define WX_ARRAYSTRING_USED
#include <wx/arrstr.h>
#endif

/** Implementing AttachSceneDialog */
class OViSEAttachSceneDialog : public AttachSceneDialog
{
private:
	bool mValid;
	wxString mResultingUniqueNameOfPrototype;

protected:
	// Handlers for AttachSceneDialog events.
	void OnCloseDialog( wxCloseEvent& event );
	void OnProtoTypeListSelect( wxCommandEvent& event );
	void OnClickCancel( wxCommandEvent& event );
	void OnClickOk( wxCommandEvent& event );
	
public:
	/** Constructor */
	OViSEAttachSceneDialog( wxWindow* parent );

	void SetAvailablePrototypes(wxArrayString ListOfAvailablePrototypes);
	wxString GetResultingUniqueNameOfPrototype();
};

#endif // __OViSEAttachSceneDialog__
