#pragma once

/**
@file
Subclass of PathConfigDialog, which is generated by wxFormBuilder.
*/

#include "MainFrameBase.h"

class OViSEPathConfigDialog : public PathConfigDialog
{
private:
	// Attributes
	wxString mInitialCmdPath;
	wxString mInitialBasePath;
	wxString mInitialMediaPath;
	wxString mCmdPath;
	wxString mBasePath;
	wxString mMediaPath;

protected:
	// Handlers for PathConfigDialog events.
	void OnClose( wxCloseEvent& event );
	void OnCmdDirChanged( wxFileDirPickerEvent& event );
	void OnBaseDirChanged( wxFileDirPickerEvent& event );
	void OnMediaDirChanged( wxFileDirPickerEvent& event );
	void OnClickCancel( wxCommandEvent& event );
	void OnClickSave( wxCommandEvent& event );

public:
	/** Constructor */
	OViSEPathConfigDialog(wxString CmdPath, wxString BasePath, wxString MediaPath, wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = wxT("Configure path settings"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize( 600,310 ), long style = wxDEFAULT_DIALOG_STYLE );
	~OViSEPathConfigDialog(void);

	void SetCmdPath(wxString CmdPath);
	void SetBasePath(wxString CmdPath);
	void SetMediaPath(wxString CmdPath);

	wxString GetCmdPath();
	wxString GetBasePath();
	wxString GetMediaPath();
};
