# -*- python -*-
Import('MODE', 'env')
LocalEnv = env.Clone()

### Setting up environment
if MODE == 'debug':
    LocalEnv.MergeFlags({'CCFLAGS':['-g','-Wall']})

project_include_paths = {'CPPPATH': Split('''#QualifiedNames
                                             #OViSEdotSceneInterpreter
                                             #OViSEdotSceneBase
                                             #OViSEAux''')}
LocalEnv.MergeFlags(project_include_paths)

project_library_paths = {'LIBPATH':['#lib/Debug']}
LocalEnv.MergeFlags(project_library_paths)

if MODE == 'debug':
    project_libs = {'LIBS':Split('''QualifiedNames
                                    OViSEdotSceneInterpreter
                                    OViSEdotSceneBase
                                    OViSEAux''')}
LocalEnv.MergeFlags(project_libs)

## Input files
input_files = Glob('*.cpp')

if MODE == 'debug':
    LocalEnv.Program(target='OViSE', source=input_files)
    LocalEnv.InstallAs('#bin/Debug/OViSE', 'OViSE')

