#ifndef OVISE_PATH_CONFIG_DLG_H
#define OVISE_PATH_CONFIG_DLG_H

/**
   @file
   Subclass of PathConfigDialog, which is generated by wxFormBuilder.
 */

#include "MainFrameBase.h"

/**
  Dialog class for first time setup.
  This dialog is displayed on first start of OViSE. It asks for the paths
  to the media and plugins folders. These values are then written to the
  application configuration (registry on Windows, config file in Linux).
*/
class OViSEPathConfigDialog : public PathConfigDialog
{
public:
	/** Constructor */
	OViSEPathConfigDialog( wxString  PluginPath,
	                       wxString  MediaPath,
	                       wxWindow* parent );
	~OViSEPathConfigDialog( void );

	wxString GetPluginPath();
	wxString GetMediaPath();
};

#endif // OVISE_PATH_CONFIG_DLG_H
