Import('env', 'myplatform')

oviseAuxEnv = env.Clone()

## Functions
def printDbg(e):
    print 'CCFLAGS:'
    print e['CCFLAGS']
    print 'CPPPATH:'
    print e['CPPPATH']
    print 'LIBPATH:'
    print e['LIBPATH']
    print 'LIBS:'
    print e['LIBS']


## Project
if(myplatform == 'Linux'):
	linux_project_include_path = {'CPPPATH':['./dotScene']}
	oviseAuxEnv.MergeFlags(linux_project_include_path)
else:
	print 'Platform not yet supported.'
	Exit(1)

## System
if(myplatform == 'Linux'):
    linux_project_cc_flags = {'CCFLAGS':Split('''-c
                                                -Wno-non-virtual-dtor
                                                -Wno-reorder
                                                -MD
                                                -fno-common''')}
    oviseAuxEnv.MergeFlags(linux_project_cc_flags)

    linux_platform_include_paths = {'CPPPATH': Split('''/usr/include/gtk-2.0
                                                        /usr/lib/gtk-2.0/include
                                                        /usr/include/cairo
                                                        /usr/include/glib-2.0
                                                        /usr/lib/glib-2.0/include
                                                        /usr/include/pango-1.0
                                                        /usr/include/atk-1.0
                                                        /usr/lib/atk-1.0/include''')}
    oviseAuxEnv.MergeFlags(linux_platform_include_paths)

    linux_platform_libraries = {'LIBS':['gcc', 'GL']}
    oviseAuxEnv.MergeFlags(linux_platform_libraries)
elif(myplatform == 'Darwin'):
    mac_platform_include_paths = {'CPPPATH':['']}
    oviseAuxEnv.MergeFlags(mac_platform_include_paths)

    mac_platform_libraries = {'LIBS':['gcc', 'System', 'stdc++', 'SystemStubs']}
    oviseAuxEnv.MergeFlags(mac_platform_libraries)
else:
    print 'Platform not yet supported.'
    Exit(1)

## Input files
if(myplatform == 'Linux'):
    input_files = Glob('*.cpp')
    input_files += Glob('dotScene/*.cpp')
elif(myplatform == 'Darwin'):
    input_files = Glob('*.cpp')
    input_files += Glob('dotScene/*.cpp')
else:
    print 'Platform not yet supported.'
    Exit(1)

## Debug
#printDbg(oviseAuxEnv)
#print COMMAND_LINE_TARGETS

oviseAuxEnv.Library('OViSEAux', input_files)