# -*- python -*-
Import('MODE', 'env')
LocalEnv = env.Clone()

### Setting up environment
if MODE == 'debug':
    LocalEnv.MergeFlags({'CCFLAGS':['-g','-Wall']})

input_files = Glob('*.cpp')

if MODE == 'debug':
    LocalEnv.Library(target='#lib/Debug/OViSEAux', source=input_files)
