#include "../ImprovedEventHandling/ImprovedEventTypes.h"

// Define events for EventListener
const wxEventType EVT_DEFAULT = wxNewEventType();
// Define events for OgreObjectListener
const wxEventType EVT_OGRE_OBJECT_CHANGED = wxNewEventType();
const wxEventType EVT_OGRE_OBJECT_CONSTRUCTED = wxNewEventType();
const wxEventType EVT_OGRE_OBJECT_DESTRUCTED = wxNewEventType();
const wxEventType EVT_OGRE_OBJECT_RENAMED = wxNewEventType();
// Declare events for Selection
const wxEventType EVT_OGRE_OBJECT_SELECTED = wxNewEventType();
const wxEventType EVT_OGRE_OBJECT_UNSELECTED = wxNewEventType();
// Define events for MovableObjectListener
const wxEventType EVT_OGRE_MOVABLEOBJECT_CHANGED  = wxNewEventType();
const wxEventType EVT_OGRE_MOVABLEOBJECT_CONSTRUCTED  = wxNewEventType();
const wxEventType EVT_OGRE_MOVABLEOBJECT_DESTRUCTED  = wxNewEventType();
const wxEventType EVT_OGRE_MOVABLEOBJECT_RENAMED  = wxNewEventType();
// Define events for CameraListener
const wxEventType EVT_OGRE_CAMERA_CHANGED  = wxNewEventType();
const wxEventType EVT_OGRE_CAMERA_CONSTRUCTED  = wxNewEventType();
const wxEventType EVT_OGRE_CAMERA_DESTRUCTED  = wxNewEventType();
const wxEventType EVT_OGRE_CAMERA_RENAMED  = wxNewEventType();
// Define events for EntityListener
const wxEventType EVT_OGRE_ENTITY_CHANGED  = wxNewEventType();
const wxEventType EVT_OGRE_ENTITY_CONSTRUCTED  = wxNewEventType();
const wxEventType EVT_OGRE_ENTITY_DESTRUCTED  = wxNewEventType();
const wxEventType EVT_OGRE_ENTITY_RENAMED  = wxNewEventType();
// Define events for LightListener
const wxEventType EVT_OGRE_LIGHT_CHANGED  = wxNewEventType();
const wxEventType EVT_OGRE_LIGHT_CONSTRUCTED  = wxNewEventType();
const wxEventType EVT_OGRE_LIGHT_DESTRUCTED  = wxNewEventType();
const wxEventType EVT_OGRE_LIGHT_RENAMED  = wxNewEventType();
// Define events for SceneManagerListener
const wxEventType EVT_OGRE_SCENEMANAGER_CHANGED  = wxNewEventType();
const wxEventType EVT_OGRE_SCENEMANAGER_CONSTRUCTED  = wxNewEventType();
const wxEventType EVT_OGRE_SCENEMANAGER_DESTRUCTED  = wxNewEventType();
const wxEventType EVT_OGRE_SCENEMANAGER_RENAMED  = wxNewEventType();
// Define events for SceneNodeListener
const wxEventType EVT_OGRE_SCENENODE_CHANGED  = wxNewEventType();
const wxEventType EVT_OGRE_SCENENODE_CONSTRUCTED  = wxNewEventType();
const wxEventType EVT_OGRE_SCENENODE_DESTRUCTED  = wxNewEventType();
const wxEventType EVT_OGRE_SCENENODE_RENAMED  = wxNewEventType();
const wxEventType EVT_OGRE_SCENENODE_MOVED  = wxNewEventType();
const wxEventType EVT_OGRE_SCENENODE_ROTATED  = wxNewEventType();
const wxEventType EVT_OGRE_SCENENODE_SCALED  = wxNewEventType();